### ISSUE TITLE
Address specification 

### ISSUE THREAD

**Issue by teemufrosen** [on-api/on-api#11] opened 2020-04-22 10:35 UTC
Please leave your feedback for the address specification in this issue. 

Describe clearly which columns you wish to leave feedback on. If you want to add new columns, describe the column that you want to add, and what purpose it will serve. 

Link to address specification: https://www.ssnf.org/globalassets/nat-i-varldsklass/rekommendationer/adressspecifikation-adresser-20150415.xlsx

**Suggestions:**

- Add MDU_COMMON to premisesType. This is already supported in ONAPI.
- servicesConnection should only support ISO-8601. YES could simply be replaced by past date, for example "2010-01-01".
- Add portCapacity so that we understand the maximum speed on the port without parsing the whole service list.
- Add cpeCapacity so that we understand if it is the CPE that limits the maximum speed available.
- Add serviceAgreement so that TL understands if the CO/NO supports the property network or not. YES/NO values.

**Comment by mchristenssonTN** [comment] 2020-04-23 06:57
I would like to add an item to premisesType: MDU_TECHNICAL. It is specified in the SSNF recommendations but not in ON API.

"MDU_TECHNICAL
Tekniskt utrymme eller gemensamt utrymme i flerbostadshus. Exempelvis larm och mätutrustning."

**Comment by thoho** [comment] 2020-04-23 09:42
Good suggestion, I second that. But also, I'd like a separate attribution for endpoints located in communal spaces, like the common recreational rooms in retirement homes with multiple apartments. "Technical" is somewhat misleading for such ports but I'm little at loss for whats the best term. Could we go with
"MDU_COMMUNAL
Gemensamhetsutrymme i flerbostadshus tillgängligt för de boende såsom samlingsrum, matsal eller liknande."
and then change "gemensamt utrymme" till "tekniskt utrymme" in the previous suggestion?
Then add this both to the address specification and in ON-API obviously.

**Comment by thoho** [comment] 2020-04-23 18:02
OK, sorry, I only checked the address specs, not the api. What does "delad fastighetsbeteckning" mean?

**Comment by mchristenssonTN** [comment] 2020-04-24 08:37
I can only guess that it tries to explain what MDU means, since the same text exist on MDU_apartment.

**Comment by junetaw** [comment] 2020-06-03 08:30
portCapacity: The maximum speed available for the port. Then we do not have to parse the services list. It is already available in the Marknadsdatabasen address data (http://www.stadsnatsportalen.se/atlas/api/spec/mdb2). This will also align the two different major data endpoints (ON-api access and MDB) more.

cityLanSegment/population: We have seen very different usage of the field population and there does not seem to be a coherent strategy in the city lans how to use this. The major issue for SPs is to know what "sub-city lan" an access is part of. Many city lans use the concept SDU and MDU and have different price depending. Example: IP-Only will soon have "IP-Only SDU" and "IP-Only MDU", we have Servanet that has different price for certain areas (Mitthem/Ragunda Hyreshus/ÅFA), Openbit with "Openbit" and "Openbit Byalag", and iTux with "iTux" and "iTux Framtiden". At the moment we rely on "text parsing certain values" or using Marknadsdatabasen as the ON-API does not contain sufficient information at the moment. If the City lans like to use the population field for their own usage (many label areas, property owner, fiber owners etc) we need a separate field to help us SPs.

**Comment by joeseos** [comment] 2020-06-04 17:45
I would like _servicesConnection_ to only support ISO-8601 (YYYY-MM-DD). IMO working with a date is preferable as it could be used to communicate a change in delivery date to end customer. YES could be replaced with the date that the installation is done. Each SP could then create their own business rules on how far into the future they will allow orders on services. Any opinions?

**Comment by thoho** [comment] 2020-06-04 20:25
Regarding the serviceConnection and from what I recall from when the address specification was developed was that "YES" was intended to be used in case the CO lacks historic information for when the access was delivered but knows that it is currently in production.
One could of course achieve the same thing with a convention, eg setting the date to 1900-01-01 if no information is available on the actual date.

**Comment by wigerhall** [comment] 2020-06-05 08:32
> portCapacity: The maximum speed available for the port. Then we do not have to parse the services list. It is already available in the Marknadsdatabasen address data (http://www.stadsnatsportalen.se/atlas/api/spec/mdb2). This will also align the two different major data endpoints (ON-api access and MDB) more.
> 
> cityLanSegment/population: We have seen very different usage of the field population and there does not seem to be a coherent strategy in the city lans how to use this. The major issue for SPs is to know what "sub-city lan" an access is part of. Many city lans use the concept SDU and MDU and have different price depending. Example: IP-Only will soon have "IP-Only SDU" and "IP-Only MDU", we have Servanet that has different price for certain areas (Mitthem/Ragunda Hyreshus/ÅFA), Openbit with "Openbit" and "Openbit Byalag", and iTux with "iTux" and "iTux Framtiden". At the moment we rely on "text parsing certain values" or using Marknadsdatabasen as the ON-API does not contain sufficient information at the moment. If the City lans like to use the population field for their own usage (many label areas, property owner, fiber owners etc) we need a separate field to help us SPs.


To have similar function as in Marknadsdatabasen we need some more fields. 
Media, portCapacity, cpeCapacity, PropertyUnitDesignation, serviceCapacity. 
As a KO we need/want to show the capabilities of the accessid in the root json response. That would be the simples way maybe. 
For an example. If a SP only provides 1 product/service of Internet 100/100. Then the Service array would only tell if the service could be added to the access (yes/no). But the SP would never know what the real capabilities is on the port without Marknadsdatabasen. 
So this is a way for KO to promote our network and for SP to get leads and maybe only need this source. 

ServiceCapacity is as calculated field (Services in MDB today) which we as a KO use to tell the SP the best guess on whats speed we can provide on a acceesid. The scenario could be that we dont have any knowledge on the CPE but we know its a rentalapartment with a ASR of 1000mbit and Media=FTTB. Then I would say for instance "1000/1000, IPTV, IPTV-VOD, VOIP" . 
I am also thing of using the current "Link-speed" value for calculating the best "ServiceCapacity". But this on is only as an idea right now.

These fields could be used to get a better picture of whats could actually be marketed on the port.

**Comment by joeseos** [comment] 2020-06-05 10:07
Please see suggestion in #12. What do you think? Should this be added to the address specification?

**Comment by JonasEklundh** [comment] 2020-11-16 15:03
> I would like _servicesConnection_ to only support ISO-8601 (YYYY-MM-DD). IMO working with a date is preferable as it could be used to communicate a change in delivery date to end customer. YES could be replaced with the date that the installation is done. Each SP could then create their own business rules on how far into the future they will allow orders on services. Any opinions?

This is how I handle it in Marknadsdatabasen - if the CO sends "YES", I set the date to "2010-01-01"

**Comment by joeseos** [comment] 2021-02-11 07:45
I've updated the original post with suggestions. 
@junetaw - I did not include any suggestions on population as I could not see a concrete suggestion - but personally I agree that population is used differently between different CO/NO. Maybe it should be split up to describe the current use cases.
 @wigerhall - Can you describe more in detail why we need to add media, portCapacity, cpeCapacity, propertyUnitDesignation and serviceCapacity? For example, what do you mean with _but the SP would never know what the real capabilities..._?

**Comment by JonasEklundh** [comment] 2021-02-11 12:44
> @wigerhall - Can you describe more in detail why we need to add media, portCapacity, cpeCapacity, propertyUnitDesignation and serviceCapacity? For example, what do you mean with _but the SP would never know what the real capabilities..._?

So if the `services` field says "100/100", the SP knows that's the max speed deliverable to the customer, but they don't know if it's due to the customer equipment or due to the port. In Marknadsdatabasen we have both `portCapacity` and `cpeCapacity` so the SP can see that the `portCapacity` is 1000 and the `cpeCapacity` is 100, so they know that they can deliver better speed if the customer upgrades their equipment, which they can communicate to the customer.

**Comment by joeseos** [comment] 2021-02-11 12:47
> > @wigerhall - Can you describe more in detail why we need to add media, portCapacity, cpeCapacity, propertyUnitDesignation and serviceCapacity? For example, what do you mean with _but the SP would never know what the real capabilities..._?
> 
> So if the `services` field says "100/100", the SP knows that's the max speed deliverable to the customer, but they don't know if it's due to the customer equipment or due to the port. In Marknadsdatabasen we have both `portCapacity` and `cpeCapacity` so the SP can see that the `portCapacity` is 1000 and the `cpeCapacity` is 100, so they know that they can deliver better speed if the customer upgrades their equipment, which they can communicate to the customer.
Thanks! I will add the suggestion to the original post.

**Comment by thoho** [comment] 2021-02-11 13:49
The "services" field has never, imho, been ment to carry specific attributes about the referenced service, just a generic reference to a service that has to have agreed upton attributes through some other means, typically technical specifications in the service agreement. Thus is is quite misleading to use examples as "100/100".

Agree that the atrributes cpeCapacity and portCapacity makes sense.

**Comment by joeseos** [comment] 2021-02-16 16:05
Any input in existing fields to align it with ONAPI? My suggestions:

servicesConnection = connection
servicesDisconnection = disconnection
coCpe = coCpeRouter

One other finding is that coNetworkAgreement is not present in the current address specification. Is this needed?

**Comment by JonasEklundh** [comment] 2021-02-17 07:37
> Any input in existing fields to align it with ONAPI? My suggestions:
> 
> servicesConnection = connection
> servicesDisconnection = disconnection
> coCpe = coCpeRouter
> 
> One other finding is that coNetworkAgreement is not present in the current address specification. Is this needed?

I'm assuming this was directed to me and in relation to Marknadsdatabasen? As you may know, Marknadsdatabasen follows the [SSNF address specifikation](https://www.ssnf.org/nat-i-varldsklass/rekommendationer/adresspecifikation/) for the common fields, which in turn is loosely based on PI-API from ComHem, and ON-API is an off-shoot of the PI-API so they have evolved and been developed separately. As far as I'm aware, ON-API did not exist when the SSNF specification was created.

So our stance is that when/if the SSNF specification is updated, we will follow that specification until we feel there is reason to discard it (i.e. if it becomes way too outdated, for example). 

A lot of customers and SP rely on the format of Marknadsdatabasen, and making cosmetic changes would undoubtedly result in lots of extra work for everyone using it, so we're wary of doing so, naturally.

**Comment by joeseos** [comment] 2021-02-17 08:23
> > Any input in existing fields to align it with ONAPI? My suggestions:
> > servicesConnection = connection
> > servicesDisconnection = disconnection
> > coCpe = coCpeRouter
> > One other finding is that coNetworkAgreement is not present in the current address specification. Is this needed?
> 
> I'm assuming this was directed to me and in relation to Marknadsdatabasen? As you may know, Marknadsdatabasen follows the [SSNF address specifikation](https://www.ssnf.org/nat-i-varldsklass/rekommendationer/adresspecifikation/) for the common fields, which in turn is loosely based on PI-API from ComHem, and ON-API is an off-shoot of the PI-API so they have evolved and been developed separately. As far as I'm aware, ON-API did not exist when the SSNF specification was created.
> 
> So our stance is that when/if the SSNF specification is updated, we will follow that specification until we feel there is reason to discard it (i.e. if it becomes way too outdated, for example).
> 
> A lot of customers and SP rely on the format of Marknadsdatabasen, and making cosmetic changes would undoubtedly result in lots of extra work for everyone using it, so we're wary of doing so, naturally.

It was a question to everyone involved in this project. Thank's for the input!

**Comment by teemufrosen** [comment] 2021-03-18 10:51
Thumbs up from me to all the suggestions added to original post!

Regarding the alignment of parameters between accesses.md and the address specification mentioned above - with respect to @JonasEklundh comment - should be done in my opinion. Address specification should be updated to use same parameters as accesses.md.

I'm interested in hearing more opinions on this.

**Comment by junetaw** [comment] 2021-05-12 09:55
cityLanSegment: Business related part of the Citylan with differences (economic or technical) from other segment.

I propose the above addition to help SP map a specific part of a CO/NO to a price list. The reasoning is as follows. 
SP receives the price list for CO/NO by paper/pdf and this might contain special parts of the CO/NO-net that has different pricing or different technical capabilities. When a SP evaluates an Access then a SP needs to be able to map that to the relevant price list.
With price list I mean the price the SP needs to pay the CO/NO as this of course impacts the price to the end customer.

Today, many SP either imports Accesses directly via CO/NO (ON-api, Brikks-api, Excelfiles, manually) or via Marknadsdatabasen. However, the structure of this data may be very different as a CO/NO might be split in several logical CityLans (I will call them "SubCityLans").  

If the SP imports Accesses from Marknadsdatabasen for a SubCityLan then the SP probably knows what price list to attach to the access unless the Accesses are split into even further different SubCityLans.

If the SP instead imports the Accesses directly from the CO/NO then the SP currently has no information regarding which SubCityLan the Access is part of unless the CO/NO for example has used Population.

Also, if the CO/NO DOES NOT separate its Accesses in SubCityLans in Marknadsdatabasen the SP currently has no information either regardless of importing the access from Marknadsdatanasen or directly from CO/NO unless the CO/NO for example has used Population.

An example is the current change in IP-Only that introduced a separate price list for SDU and MDU. The Accesses imported from their ON-api does currently not have any readily available information of which part the Access belongs to. Currently, the SPs only way is to iterate AvailableServices and look for (or lack of) the word "MDU" in the technical servies name. Only then the SP knows which price list to apply. 

Another example is several CO/NO that has one price list for their own fiber network and another for fibers owned by a fiber association (usually called Byalag or similar). They usually add a new CO/NO to Marknadsdatabasen but they of course have the same ON-api for service activation. If the SP imports from Marknadsdatabasen then the price list is known, if the SP import from CO/NO directly the price list is not known unless the CO/NO for example has been kind to reserv the Population field to help the SP. 

Here is some more CO/NO:
Openbit:
 - Stadnät:
    How to know price list: Import from SubCityLan in MdB OR parse Access.Population=Stadsnät
 - Byalag: 
    How to know price list: Import from SubCityLan in MdB OR parse Access.Population=Byalag

Bosnet:
 - Stadnät:
    How to know price list: Import from SubCityLan in MdB.
 - Byalag: 
    How to know price list: Import from SubCityLan in MdB.

IP-Only:
    How to know price list: Parse Access.AvailableServices looking for specific strings (or lack of).

iTUX:
- Special price for one population. All share same api.
    How to know price list: Parse Population=Framtiden and set special price, all other populations into default price list.

---
I think there is also the need to discuss what a CO/NO should be in terms of api and accesses. It is a hierarchy or should they be considered different entities? Should a CityLan-entity be a homogeneous collection of accesses all having the same price list and same technical capabilities?
Should for example iTUX Framtiden be considered a CityLan and the rest of iTUX another?
Should IP-Only MDU be one, IP-Only SDU another and IP-Only City a third?

When SP query the CO/NO the SP adds "SubCityLan" into the query to get that SubCityLan only. 
Import of accesses ALWAYS has a connection to a price list by way of a SubCityLan.
The CO/NO runs one instance of ON-api but handles different SubCityLans and can be split into X different portions.

**Comment by junetaw** [comment] 2021-06-22 10:34
Note: With the future implementation of priceGroup the following may or may not be relevant.

premisesType: Is there a need to add two more enumerations for Holiday homes (Fritidsboenden)? Example HOLIDAY_HOUSE and HOLIDAY_MDU_APARTMENT.
In certain CO there is a separation of prices and/or technical services depending if the access is a residential or holiday house/apartment. For example you could have a "base" internet service (say 2/2 Mbit/s) for IoT that is active all year but the owner/renter could upgrade to a faster one for 1-x days and then it returns to the base. This is only available to Holiday homes.

In order to "know" it might be necessary to introduce two or more new enums.
Opinions?

**Comment by joeseos** [comment] 2021-06-27 17:21
> Note: With the future implementation of priceGroup the following may or may not be relevant.
> 
> premisesType: Is there a need to add two more enumerations for Holiday homes (Fritidsboenden)? Example HOLIDAY_HOUSE and HOLIDAY_MDU_APARTMENT.
> In certain CO there is a separation of prices and/or technical services depending if the access is a residential or holiday house/apartment. For example you could have a "base" internet service (say 2/2 Mbit/s) for IoT that is active all year but the owner/renter could upgrade to a faster one for 1-x days and then it returns to the base. This is only available to Holiday homes.
> 
> In order to "know" it might be necessary to introduce two or more new enums.
> Opinions?

Should’t this be covered by population? 

I’ve forgot the name, but are these the same as the ones that doesn’t have it’s own formal address according to Lantmäteriet? Imo, this kind of houses/ports should have it’s own premisesType instead of OTHER.

**Comment by JonasEklundh** [comment] 2021-06-28 10:05
> Should’t this be covered by population?

"population" is one of the worst fields in the ON-API and SSNF specification, since it has no formal rules what it should contain, so CO's use it as they see fit and you need a dialog with each CO on how to interpret and use that information.

premisesType is a set list of types that a premise can have. There are more options in Marknadsdatabasen than in ON-API but summer homes isn't included in MdB either, and perhaps it should be.

**Comment by joeseos** [comment] 2021-06-29 17:02
> > Should’t this be covered by population?
> 
> "population" is one of the worst fields in the ON-API and SSNF specification, since it has no formal rules what it should contain, so CO's use it as they see fit and you need a dialog with each CO on how to interpret and use that information.
> 
> premisesType is a set list of types that a premise can have. There are more options in Marknadsdatabasen than in ON-API but summer homes isn't included in MdB either, and perhaps it should be.

I agree that population is loosly described and that it can be used basically in whatever way the CO sees reasonable. However, usually it’s used to differentiate pricing between differens sub networks. My point is just that population and premisesType have their separate uses, despite how unclear population might be. 
Example: if only premisesType is used to decide the different pricing, what happends when a SDU_COMMON is added to the ”pricing list”?
And just to be clear, I think it’s a good idea to add support for more premises types, but maybe not for that specific use case.

**Comment by junetaw** [comment] 2023-05-25 12:07
`premisesType` is also being discussed separately in #92

**Comment by junetaw** [comment] 2024-01-18 15:23
I move to suggest to close this as I think most is covered in other issues.

**Comment by junetaw** [comment] 2024-02-05 20:32
Address specification has a separate working group that processes this. It has an own channel on slack for inputs from outside.
The above discussion is largely obselete. I close this.

**Closed by junetaw** 2024-02-05 20:32 UTC
Labels: question
